#!/usr/bin/env php
<?php

require __DIR__.'/vendor/docopt/docopt/src/docopt.php';

$doc = <<<'DOCOPT'
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help                     Show this screen
  -v --version                  Show version
  --format <fmt>                Report format [default: stylish]
DOCOPT;

$args = Docopt::handle($doc, array('version'=>'v0.0.1'));
foreach ($args as $k=>$v)
    echo $k.': '.json_encode($v).PHP_EOL;

function genDiff($args)
{
    $file1 = json_decode(file_get_contents($args['<firstFile>']), true);
    $file2 = json_decode(file_get_contents($args['<secondFile>']), true);
    $diff = array_merge($file1, $file2);
    return json_encode ($diff);
}
echo(genDiff($args));
