#!/usr/bin/env php
<?php

//Подгрузка необходимого>>>
require __DIR__.'/src/docopt.php';
/*$autoloadPath1 = __DIR__ . '/../../../autoload.php';
$autoloadPath2 = __DIR__ . '/vendor/autoload.php';

if (file_exists($autoloadPath1)) {
    require_once $autoloadPath1;
} else {
    require_once $autoloadPath2;
}*/
//<<<Подгрузка необходимого

$doc = <<<'DOCOPT'
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help                     Show this screen
  -v --version                  Show version
  --format <fmt>                Report format [default: stylish]
DOCOPT;

$args = Docopt::handle($doc, array('version'=>'v0.0.1'));
foreach ($args as $k=>$v)
    echo $k.': '.json_encode($v).PHP_EOL;

function genDiff($args)
{
    $file1 = json_decode(file_get_contents($args['<firstFile>']), true);
    $file2 = json_decode(file_get_contents($args['<secondFile>']), true);
    $diff = array_merge($file1, $file2);
    return json_encode ($diff);
}
echo(genDiff($args));
